---
apiVersion: v1
kind: Secret
metadata:
  name: backupprovider
  namespace: garden
type: Opaque
data:
  accessKeyID: Zm9v # foo
  secretAccessKey: YmFy # bar
  endpoint: aHR0cDovL3Jvb2stY2VwaC1yZ3ctb2NzLXN0b3JhZ2VjbHVzdGVyLWNlcGhvYmplY3RzdG9yZS5vcGVuc2hpZnQtc3RvcmFnZS5zdmM= # http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc
  disableSSL: dHJ1ZQ== # true
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupBucket
metadata:
  name: cloud--openshift--fg2d6
spec:
  type: OCS
  region: ocs-storagecluster-cephobjectstore
  secretRef:
    name: backupprovider
    namespace: garden
