apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup
  namespace: shoot--foobar--openshift
type: Opaque
data:
  accessKeyID: Zm9v # foo
  secretAccessKey: YmFy # bar
  endpoint: aHR0cDovL3Jvb2stY2VwaC1yZ3ctb2NzLXN0b3JhZ2VjbHVzdGVyLWNlcGhvYmplY3RzdG9yZS5vcGVuc2hpZnQtc3RvcmFnZS5zdmM= # http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc
  disableSSL: dHJ1ZQ== # true
  bucketName: Y2xvdWQtLW9wZW5zaGlmdC0tZmcyZDY= # cloud--openshift--fg2d6
  region: b2NzLXN0b3JhZ2VjbHVzdGVyLWNlcGhvYmplY3RzdG9yZQ== # ocs-storagecluster-cephobjectstore
