image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/provider-openshift
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
maxUnavailable: 1
maxSurge: 50%

resources: {}
vpa:
  enabled: true
# resourcePolicy:
#   minAllowed:
#     cpu: 100m
#     memory: 128Mi
  updatePolicy:
    updateMode: "Auto"

controllers:
  backupbucket:
    concurrentSyncs: 5
  backupentry:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
