---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
rules:
- apiGroups:
  - extensions.gardener.cloud
  resources:
  - clusters
  - backupbuckets
  - backupbuckets/status
  - backupentries
  - backupentries/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  resourceNames:
  - provider-openshift-leader-election
  verbs:
  - get
  - watch
  - update
  - patch
- apiGroups:
  - ""
  - apps
  - batch
  - rbac.authorization.k8s.io
  - admissionregistration.k8s.io
  - apiextensions.k8s.io
  resources:
  - namespaces
  - namespaces/finalizers
  - events
  - secrets
  - configmaps
  - endpoints
  - deployments
  - statefulsets
  - services
  - serviceaccounts
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  - jobs
  - pods
  - pods/log
  - mutatingwebhookconfigurations
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
